MOUSEKEY_ENABLE = yes    # Mouse keys
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
SRC += features/flow.c
SRC += features/select_word.c
SRC += features/layer_lock.c
LEADER_ENABLE = yes
