MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = no    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
SRC += features/flow.c
SRC += features/select_word.c
SRC += features/layer_lock.c
LEADER_ENABLE = yes
EXTRAKEY_ENABLE = yes
SRC += features/achordion.c
